### ISSUE TITLE
Creating a cookiecutter mesa model by running mesa startproject fails

### ISSUE THREAD

**Issue by freinhard** [projectmesa/mesa#1606]
**Describe the bug**
I tried to start a new mesa project using `mesa startproject`

**Expected behavior**
A mesa project should be added.

**To Reproduce**
```
(env) > $ mesa startproject                                                                                                 
project [Example Project]: Test
snake [test]: test
camel [Test]: Test
agent [TestAgent]: TestAgent
model [TestModel]: TestModel
description [Example short description of the project]: Test description

Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/cli.py", line 194, in main
    cookiecutter(
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/main.py", line 114, in cookiecutter
    result = generate_files(
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/generate.py", line 281, in generate_files
    template_dir = find_template(repo_dir)
  File "/usr/local/lib/python3.10/site-packages/cookiecutter/find.py", line 31, in find_template
    raise NonTemplatedInputDirException
cookiecutter.exceptions.NonTemplatedInputDirException
```

**Comment by rht** [comment]
I can't reproduce the problem. What is the Mesa version you have? Have you made sure that you are on the latest version of Mesa (make sure to check your current version before updating)?

**Comment by freinhard** [comment]
Thanks @rht!

```
(env) > $ pip show mesa                                                        
Name: Mesa
Version: 1.1.1
Summary: Agent-based modeling (ABM) in Python 3+
Home-page: https://github.com/projectmesa/mesa
Author: Project Mesa Team
Author-email: projectmesa@googlegroups.com
License: Apache 2.0
Location: /usr/local/lib/python3.10/site-packages
Requires: click, cookiecutter, networkx, numpy, pandas, tornado, tqdm
Required-by: 
```

**Comment by rht** [comment]
I finally reproduced the problem in the latest release. It works on my machine because I did `pip install -e .` instead of `pip install .`

This PR should fix it: #1611. I have tested this on my machine.

https://github.com/projectmesa/mesa/commit/a8c889e4490e4b8a5314b88a8e9e39e407f561c7

Earlier attempt was: https://github.com/projectmesa/mesa/commit/a8c889e4490e4b8a5314b88a8e9e39e407f561c7. But it looks like it worked in the past, but no longer work in the present.

@jackiekazil @tpike3 should we release 1.2.1 for this?

**Comment by jackiekazil** [comment]
We could do that.

**Comment by freinhard** [comment]
Thanks! 😀
