### ISSUE TITLE
TyperError when model reporter is a partial function

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa#1871]
**Describe the bug**
 
```bash
$ python3 scripts/run.py --campus ub

Traceback (most recent call last):
  File "/Users/boyu/GitHubProjects/mesa-examples/gis/agents_and_networks/scripts/run.py", line 57, in <module>
    server = mesa.visualization.ModularServer(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boyu/GitHubProjects/mesa-examples/venv/lib/python3.11/site-packages/mesa/visualization/ModularVisualization.py", line 355, in __init__
    self.reset_model()
  File "/Users/boyu/GitHubProjects/mesa-examples/venv/lib/python3.11/site-packages/mesa/visualization/ModularVisualization.py", line 382, in reset_model
    self.model = self.model_cls(**model_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/boyu/GitHubProjects/mesa-examples/gis/agents_and_networks/src/model/model.py", line 127, in __init__
    self.datacollector.collect(self)
  File "/Users/boyu/GitHubProjects/mesa-examples/venv/lib/python3.11/site-packages/mesa/datacollection.py", line 182, in collect
    self.model_vars[var].append(reporter())
                                ^^^^^^^^^^
TypeError: get_num_commuters_by_status() missing 1 required positional argument: 'model'
```

**Expected behavior**

The example model is expected to run without errors.

**To Reproduce**

Run the https://github.com/projectmesa/mesa-examples/tree/main/gis/agents_and_networks example model with latest Mesa, Mesa-Geo and Mesa-Viz-Tornado

**Additional context**

In the example model, the model reporters are `partial` functions:

https://github.com/projectmesa/mesa-examples/blob/10985d44091b9ba1ecebd013d2d2252e2116649b/gis/agents_and_networks/src/model/model.py#L21-L41

https://github.com/projectmesa/mesa-examples/blob/10985d44091b9ba1ecebd013d2d2252e2116649b/gis/agents_and_networks/src/model/model.py#L111-L126

But the support for `partial` functions were dropped in https://github.com/projectmesa/mesa/commit/64ce41627dfba200451c8b43f13611568b10660c while dealing with attribute strings.

As a result, when `partial` functions are used, they are added in this way:

https://github.com/projectmesa/mesa/blob/2505ba408fa1d9e20046c2184406e869c1e4d4eb/mesa/datacollection.py#L200-L203

**Comment by wang-boyu** [comment]
This was fixed previously but was introduced again in https://github.com/mesa/mesa/pull/2605, where partial function model reporter is not checked. This resulted in a failed test for gis examples: https://github.com/mesa/mesa-geo/actions/runs/21463247809/job/61819937720 because some model reporters are partial functions: https://github.com/mesa/mesa-examples/blob/2bc88ae214ca252440062f9320bcd7a21dc363ba/gis/agents_and_networks/src/model/model.py#L119
