### ISSUE TITLE
Schelling example has an import issue

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#274]
```
 python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from server import server
  File "/Users/fje630/Projects/code/classes/mesa/mesa/examples/Schelling/server.py", line 1, in <module>
    from mesa.visualization.ModularVisualization import ModularServer
ImportError: No module named mesa.visualization.ModularVisualization
```

**Comment by jackiekazil** [comment]
This is not an issue. I don't want to talk about it.

**Comment by Omkar28** [comment]
?

**Comment by Omkar28** [comment]
did you solve the error
