### ISSUE TITLE
Discuss: Format of helpful error messages

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#580]
So, the other day I was trying to use Simultaneous activation and I forgot to put and advance function on my agent. And I got an error that wasn't helpful. 

I thought we should have more helpful errors. Something like.... 

```python
class SimultaneousActivation(BaseScheduler):
    """ A scheduler to simulate the simultaneous activation of all the agents.

    This scheduler requires that each agent have two methods: step and advance.
    step() activates the agent and stages any necessary changes, but does not
    apply them yet. advance() then applies the changes. """ 

 
    def step(self):
        """ Step all agents, then advance them. """
        agent_keys = list(self._agents.keys())
        for agent_key in agent_keys:
            self._agents[agent_key].step()
        for agent_key in agent_keys:
            try:
                self._agents[agent_key].advance()
            except AttributeError:
                print("SimultaneousActivation requires each agent to have an advance method.")
                raise
        self.steps += 1
        self.time += 1
```
Which would result it... 

```
SimultaneousActivation requires each agent to have an advance method.
ERROR:tornado.application:Uncaught exception in /ws
Traceback (most recent call last):
  File "/Users/fje630/Projects/envs/dec15sev1/lib/python3.6/site-packages/tornado/websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "/Users/fje630/Projects/code/mesa/mesa/mesa/visualization/ModularVisualization.py", line 199, in on_message
    self.application.model.step()
  File "/Users/fje630/Projects/code/modeling/IOModel/IOModel/IOModel/model.py", line 51, in step
    self.schedule.step()
  File "/Users/fje630/Projects/code/mesa/mesa/mesa/time.py", line 124, in step
    self._agents[agent_key].advance()
AttributeError: 'AppAgent' object has no attribute 'advance'
```

Is that helpful? I am wondering if that message doesn't get lost in the error. Thoughts? 

Maybe... 
```
MESA: SimultaneousActivation requires each agent to have an advance method.
```

Or maybe print in colors using https://pypi.org/project/termcolor/?

**Comment by Corvince** [comment]
Yes, I think an error message on top really does get lost. 

Instead of 
``` PYTHON
            except AttributeError:
                print("SimultaneousActivation requires each agent to have an advance method.")
                raise
```
why not use
``` PYTHON
            except AttributeError:
                raise AttributeError("SimultaneousActivation requires each agent to have an advance method.")
```
That will put your message at the end of the error message. Since this would remove the line
`AttributeError: 'AppAgent' object has no attribute 'advance'`
it might be better to define an own Error class

Definitely a good idea

**Comment by quaquel** [comment]
We are moving towards relying more on specialized mesa exceptions so this issue is being addressed.
