### ISSUE TITLE
attribute error: 'MyAgent' object has no attribute 'name'

### ISSUE THREAD

**Issue by vklimaj** [projectmesa/mesa#604]
Hi,

I'm trying to complete the Mesa tutorial (https://media.readthedocs.org/pdf/mesa/latest/mesa.pdf) and am running into repeated attribute errors.

For example, I just tried this code (exactly as it's printed in the tutorial):
```
import random
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid

class MyAgent(Agent):
   def __init__(self, name, model):
      super().__init__(name, model)
   def step(self):
      print("{} activated".format(self.name))
        
class MyModel(Model):
    def __init__(self, n_agents):
        self.schedule = RandomActivation(self)
        self.grid = MultiGrid(10, 10, torus=True)
        for i in range(n_agents):
            a = MyAgent(i, self)
            self.schedule.add(a)
            coords = (random.randrange(0, 10), random.randrange(0, 10))
            self.grid.place_agent(a, coords)
    def step(self):
        self.schedule.step()
```
        
and ran it with this:
```
model = MyModel(5)
model.step()
```
And I got the following error:

```
 Traceback (most recent call last):

  File "<ipython-input-37-0a123724f15a>", line 2, in <module>
    model.step()

  File "<ipython-input-36-121370ba2212>", line 11, in step
    self.schedule.step()

  File "/anaconda3/lib/python3.6/site-packages/mesa/time.py", line 113, in step
    agent.step()

  File "<ipython-input-35-a01ea06bc9ce>", line 5, in step
    print("{} activated".format(self.name))

AttributeError: 'MyAgent' object has no attribute 'name'
```
Any idea how to fix this?  

I'm somewhat of a beginner, so it's possible I'm missing some obvious fixes. 

Thanks!

**Comment by vklimaj** [comment]
Hi, 

It appears that adding the line "self.name = name" to init fixed the problem. If anyone else is having this issue, try having your MyAgent class reads as follows:

```
class MyAgent(Agent):
    def __init__(self, name, model):
        self.name = name
        super().__init__(name, model)
    def step(self):
        print("{} activated".format(self.name))

```
