### ISSUE TITLE
virus_on_network error

### ISSUE THREAD

**Issue by ammarqureshi** [projectmesa/mesa#644]
**Describe the bug**
```
Ammars-MacBook-Pro:virus_on_network ammarqureshi$ python run.py 
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from virus_on_network.server import server
  File "/Users/ammarqureshi/mesa/mesa/examples/virus_on_network/virus_on_network/server.py", line 84, in <module>
    server = ModularServer(VirusOnNetwork, [network, MyTextElement(), chart], 'Virus Model', model_params)
  File "/Users/ammarqureshi/anaconda/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 276, in __init__
    self.reset_model()
  File "/Users/ammarqureshi/anaconda/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 302, in reset_model
    self.model = self.model_cls(**model_params)
  File "/Users/ammarqureshi/mesa/mesa/examples/virus_on_network/virus_on_network/model.py", line 42, in __init__
    self.grid = NetworkGrid(self.G)
  File "/Users/ammarqureshi/anaconda/lib/python3.6/site-packages/mesa/space.py", line 784, in __init__
    for node_id in self.G.nodes:
TypeError: 'method' object is not iterable
```
**Expected behavior**
should run the model

**To Reproduce**
``` python run.py```

**Additional Context**
```
Ammars-MacBook-Pro:virus_on_network ammarqureshi$ pip install -r requirements.txt
Requirement already satisfied: networkx in /Users/ammarqureshi/anaconda/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (1.11)
Requirement already satisfied: decorator>=3.4.0 in /Users/ammarqureshi/anaconda/lib/python3.6/site-packages (from networkx->-r requirements.txt (line 1)) (4.0.11)

```

**Comment by Corvince** [comment]
Mesa requires a version of `networkx >= 2`

This should be in the requirements file, thanks for reporting!
