### ISSUE TITLE
Example virus_on_network failing for networkx (2.4) - 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by roguetrainer** [projectmesa/mesa#761]
I am unable to run the example `virus_on_network`.

The error log is:

> Running C:\Users\Guest user\github\mesa\examples\virus_on_network\run.py
> The interactive Python process has exited.
> Traceback (most recent call last):
>   File "C:\Users\Guest user\github\mesa\examples\virus_on_network\run.py", line 1, in <module>
>     from virus_on_network.server import server
>   File "C:\Users\Guest user\github\mesa\examples\virus_on_network\virus_on_network\server.py", line 84, in <module>
>     server = ModularServer(VirusOnNetwork, [network, MyTextElement(), chart], 'Virus Model', model_params)
>   File ".\mesa\visualization\ModularVisualization.py", line 274, in __init__
>     self.reset_model()
>   File ".\mesa\visualization\ModularVisualization.py", line 300, in reset_model
>     self.model = self.model_cls(**model_params)
>   File "C:\Users\Guest user\github\mesa\examples\virus_on_network\virus_on_network\model.py", line 60, in __init__
>     self.grid.place_agent(a, node)   
>   File ".\mesa\space.py", line 788, in place_agent   
>     self._place_agent(agent, node_id)   
>   File ".\mesa\space.py", line 810, in _place_agent   
>     self.G.node[node_id]['agent'].append(agent)    
> AttributeError: 'Graph' object has no attribute 'node' 

  
**`AttributeError: 'Graph' object has no attribute 'node'`**

Possibly this is due to a change in `networkx` package?
[https://networkx.github.io/documentation/stable/release/release_2.4.html#deprecations]()

> `G.node –> use G.nodes`

Presumably the work-around is to use an earlier version of `networkx`?

**Comment by roguetrainer** [comment]
Rolled back to version networkx==2.2 using `pip install networkx==2.2` & this example works fine.
