### ISSUE TITLE
Bug in wolf_sheep example (test_random_walk.py)

### ISSUE THREAD

**Issue by jjgomezcadenas** [projectmesa/mesa#816]
**Describe the bug**
 Running test_random_walk.py results in a failure

Traceback (most recent call last):
  File "test_random_walk.py", line 81, in <module>
    viz.step()
  File "/Users/jjgomezcadenas/Projects/Development/src/mesa/mesa/visualization/TextVisualization.py", line 57, in step
    self.model.step()
  File "test_random_walk.py", line 53, in step
    self.schedule.step()
  File "/Users/jjgomezcadenas/Projects/Development/src/mesa/mesa/time.py", line 120, in step
    agent.step()
  File "test_random_walk.py", line 20, in step
    self.random_move()
  File "/Users/jjgomezcadenas/Projects/Development/mesaTutorials/wolf_sheep/wolf_sheep/random_walk.py", line 39, in random_move
    next_moves = self.model.grid.get_neighborhood(self.pos, self.moore, True)
AttributeError: 'bool' object has no attribute 'grid'

**Expected behavior**
The script is expected to test the RandomWalker.py class. It actually finds a bug in that class. The bug is in the line

a = WalkerAgent((x, y), self, True)

which should read, I think:

a = WalkerAgent(i, (x, y), self, True) 

**To Reproduce**
The bug can be reproduced running the script test_randomw_walk.py

**Additional context**
Once introduced the trivial fix the code runs correctly.

**Comment by jackiekazil** [comment]
Ty for the submission. I submitted a PR to fix this. 
Feel free to submit a PR directly. We appreciate contributions! 

Closing this ticket in lieu of the PR at #821.
