### ISSUE TITLE
Runtime Error when using Multi-Processing using batch runner on windows machine

### ISSUE THREAD

**Issue by reevesj191** [projectmesa/mesa#952]
**Describe the bug**

I am trying to use the BatchrRunnerMP() function to run several iterations of the model at once. When I run the code, it does not crash but a RuntimeError is continuously returned. It states: 

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

I have provided the code below but I think this is an issue with the operating system. The code runs fine on my laptop running MacOS but when I move it over to my work computer (Windows) it returns this error. I would be great if I could run this on my work computer as it has 40 cores and would dramatically speed up the process.

Thanks.

**To Reproduce**

This is the code that I am using to run the task. 

from Model_definition import *
from mesa.batchrunner import BatchRunner, BatchRunnerMP

fixed_params = {"width": 500,
                "height": 500,
                "Na": 50,
                "treesdie": True,
                "max_ts": (1000000)
}

variable_params = {
    "Ns": (10, 20, 30, 40),
    "Nn": (10, 20, 30, 40),
    "tool_acq": ("nearest","random")
}

mp_batch_run = BatchRunnerMP(model_cls=PrimToolModel,
                             nr_processes=4,
                             variable_parameters=variable_params,
                             fixed_parameters=fixed_params,
                             iterations=30)

mp_batch_run.run_all()

**Additional context**

**Comment by tpike3** [comment]
@reevesj191 We have an update going through the final approval stages that makes BatchRunner compatible with Windows, but it has not been released to PyPI. If you install from git by doing 
```
pip install git+https://github.com/projectmesa/mesa.git
```
It should work on both your MacOS and WIndows machine

**Comment by tpike3** [comment]
@reevesj191 Just following up to see if this issue is resolved.  If nothing heard I will assume batchrunner is working for you.

**Comment by reevesj191** [comment]
Thanks for following up. I tried it out my laptop over the Christmas and it worked perfectly fine. I am back in at work tomorrow so I will try it out on my desktop machine just to make sure it works there too. 

I will let you know tomorrow. Thanks for your patience!

**Comment by reevesj191** [comment]
@tpike3 Thanks again for your patience. I installed Mesa on my desktop from Git today. I tried using BatchRunnerMP and unfortunately it returned the same error repetitive error as shown above. I tried it on python 3.8 and python 3.9. I also installed python 3.6 just to see if that made a difference and it returned the same error.

**Comment by tpike3** [comment]
@reevesj191 I am very sorry, I do not know how I missed your reply.  For your desktop, are you using the lines

```

        if __name__ == '__main__':
            freeze_support()
            <initiate and run model>
```

This is definitely a necessity on windows machines

**Comment by christino156** [comment]
Just wanted to mention that I had the same problem as @reevesj191 but the last comment fixed my issue. Thanks a lot @tpike3!

**Comment by tpike3** [comment]
As this seems to be resolved, I am going to close this issue.

**Comment by EwoutH** [comment]
Unfortunately I still have an similar issue using Windows.

`Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ewout\Documents\GitHub\EPA1352-Adv-Simulation\EPA1352-G06-A2\model\experiments.py", line 13, in <module>
    results = batch_run(model_cls=BangladeshModel, parameters=par_dict, number_processes=None, iterations=1, data_collection_period=-1, max_steps=run_length, display_progress=True)
  File "C:\Users\Ewout\.virtualenvs\Py310\lib\site-packages\mesa\batchrunner.py", line 98, in batch_run
    with Pool(number_processes) as p:
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Ewout\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
I see that the tests, [test_batchrunnerMP.py#L268](https://github.com/projectmesa/mesa/blob/main/tests/test_batchrunnerMP.py#L268), explicitly add the following part before running `unittest.main()`.
```
if __name__ == "__main__":
    freeze_support()
```
Should this be added on other places as well?

**Comment by tpike3** [comment]
Regarding batch_run, I think we need to add a footnote for Windows machines in tutorial. If I run on Windows locally I have to add the lines:
```
if __name__ == '__main__':
      freeze_support()
```
However, somehow through pytest and the build  on Windows 3.10 this is not an issue and I do not know why.  I know @Corvince did not have this issue when he was building it and he was using a Windows machine. I am wondering if it may be an IDE issue.

**Comment by EwoutH** [comment]
Where do you have to add them exactly?

**Comment by tpike3** [comment]
Typically in your ```run.py``` file. 

```

if __name__ == '__main__':
      freeze_support()
      result = batch_run(SomeModel, parameters = <some params>)

```
